In [1]:
import pandas as pd
import numpy as np 
import yfinance as yf
from preprocessing.data import calculate_features
from signals.meanreversion import mean_reversion

In [2]:
ticker = yf.Ticker("AAPL")
data = ticker.history(start = "2020-04-01", end = "2020-05-01")

In [3]:
data = calculate_features(data)
data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Close_lag,return,return_lag,direction
Date,,,,,,,,,,,
2020-04-01 00:00:00-04:00,59.505966,60.041882,57.726823,58.156521,176218400,0.0,0.0,NaN,NaN,NaN,NaN
2020-04-02 00:00:00-04:00,58.018920,59.180070,57.188491,59.126961,165934000,0.0,0.0,58.156521,0.016549,NaN,NaN
2020-04-03 00:00:00-04:00,58.612769,59.312837,57.688193,58.277218,129880000,0.0,0.0,59.126961,-0.014476,0.016549,1.0
2020-04-06 00:00:00-04:00,60.568146,63.515681,60.201216,63.361187,201820400,0.0,0.0,58.277218,0.083640,-0.014476,-1.0
2020-04-07 00:00:00-04:00,65.372061,65.589330,62.523502,62.627304,202887200,0.0,0.0,63.361187,-0.011650,0.083640,1.0

In [4]:
temp = mean_reversion(data)
temp.head()

                sum      mean  count
direction
-1.0       0.153628  0.019204      8
 1.0       0.028298  0.002573     11

                sum      mean  count
direction
-1.0       0.153628  0.019204      8
 1.0       0.028298  0.002573     11